import { useEffect, useState } from 'react'
import { Activity, ArrowLeft, ArrowUpRight, Check, ChevronRight, Download, FileCode2, FlaskConical, Focus, Layers, LoaderCircle, ScanLine, SlidersHorizontal, Table2, ZoomIn, ZoomOut } from 'lucide-react'
import { PixelSlice } from './PixelSlice'
import { SurfaceView } from './SurfaceView'
import { labelName, number } from './types'
import type { Case, Manifest, Plane } from './types'
import './demo.css'

const planes:Plane[]=['sagittal','coronal','axial']
const axes:Record<Plane,number>={sagittal:0,coronal:1,axial:2}
const flagNames:Record<string,string>={remaining_disconnected_components:'Fragmented',scan_boundary_component_preserved:'Scan boundary',centroid_order_review:'Identity order',removal_exceeds_2_percent_review:'>2% removed'}
const presets={Bone:[700,250],'Soft tissue':[400,40],Lung:[1500,-600]}
const nearest=(item:Case,plane:Plane,index:number)=>item.frames[plane].reduce((best,frame,i,frames)=>Math.abs(frame.index-index)<Math.abs(frames[best].index-index)?i:best,0)
function ComponentsChart({item,onSelect}:{item:Case;onSelect:(id:number)=>void}) {
  const rows=item.labels,maximum=Math.max(...rows.map(label=>label.before_components),1),height=126,width=624
  return <div className="vd-chart-wrap"><div className="vd-chart-legend"><span><i/> Before</span><span><i/> After</span><small>Click a vertebra to isolate its prediction</small></div>
    <svg viewBox={`0 0 ${width} 180`} role="img" aria-label="Connected components for all 24 vertebrae before and after refinement">
      {[0,Math.ceil(maximum/2),maximum].map(value=><g key={value}><line x1={28} x2={width-6} y1={144-value/maximum*height} y2={144-value/maximum*height} stroke="#edf0f3"/><text x={20} y={147-value/maximum*height} textAnchor="end" fill="#97a0aa" fontSize={9}>{value}</text></g>)}
      {rows.map((label,index)=>{const x=34+index*24;return <g key={label.id} tabIndex={0} role="button" aria-label={`Inspect ${labelName(label.name)}`} onClick={()=>onSelect(label.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(label.id)}}} className="vd-chart-bar"><title>{labelName(label.name)}: {label.before_components} → {label.after_components} components</title><rect x={x} y={144-label.before_components/maximum*height} width={8} height={label.before_components/maximum*height} fill="#c8ced5" rx={1}/><rect x={x+9} y={144-label.after_components/maximum*height} width={8} height={label.after_components/maximum*height} fill="#4b5665" rx={1}/><text x={x+8} y={164} textAnchor="middle" fill="#7d8793" fontSize={9}>{labelName(label.name)}</text></g>})}
    </svg>
  </div>
}
export default function VertebraeDemo() {
  const [manifest,setManifest]=useState<Manifest|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0)
  const [caseId,setCaseId]=useState('BDMAP_00000031'),[plane,setPlane]=useState<Plane>('sagittal'),[positions,setPositions]=useState<Record<Plane,number>>({sagittal:0,coronal:0,axial:0})
  const [selected,setSelected]=useState<number[]>([]),[windowWidth,setWindowWidth]=useState(700),[level,setLevel]=useState(250),[opacity,setOpacity]=useState(.55),[zoom,setZoom]=useState(1),[focus,setFocus]=useState(false)
  const [scope,setScope]=useState('all'),[labelsOpen,setLabelsOpen]=useState(false)
  useEffect(()=>{
    const previousTitle=document.title,canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]'),previousCanonical=canonical?.href
    document.body.classList.add('vd-body');document.title='Vertebrae Study · Hongkang Chu'
    if(canonical)canonical.href='https://chuhongkang.com/projects/vertebrae/'
    return()=>{document.body.classList.remove('vd-body');document.title=previousTitle;if(canonical&&previousCanonical)canonical.href=previousCanonical}
  },[])
  useEffect(()=>{
    const controller=new AbortController();setError('')
    fetch(`/api/demo/vertebrae.${import.meta.env.VITE_DEMO_VERSION}.json`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('The research data could not be loaded.');setManifest(await response.json())}).catch(err=>{if(!controller.signal.aborted)setError(err.message)})
    return()=>controller.abort()
  },[attempt])
  const item=manifest?.cases.find(item=>item.id===caseId)??manifest?.cases[0]
  useEffect(()=>{
    if(!item)return
    setPositions(Object.fromEntries(planes.map(plane=>[plane,nearest(item,plane,item.initial_indices[plane])])) as Record<Plane,number>)
    setSelected(item.labels.filter(label=>label.before_voxels>0||label.after_voxels>0).map(label=>label.id));setZoom(1);setFocus(false)
  },[item])
  if(!manifest||!item)return <div className="vd vd-loading"><a href="/"><ArrowLeft size={15}/> Hongkang Chu</a><FlaskConical size={28}/><h1>Vertebrae Study</h1><p role={error?'alert':'status'}>{error||'Loading the research workbench…'}</p>{error?<button className="vd-button" onClick={()=>setAttempt(value=>value+1)}>Try again</button>:<LoaderCircle className="vd-spin"/>}</div>
  const frames=item.frames[plane],position=Math.min(positions[plane],frames.length-1),frame=frames[position]
  const present=item.labels.filter(label=>label.before_voxels>0||label.after_voxels>0),flagged=present.filter(label=>label.flags.length>0)
  const volume=item.labels.reduce((value,label)=>value+label.before_volume_ml-label.after_volume_ml,0)
  const rows=scope==='flagged'?flagged:present
  const inspect=()=>{setPositions(Object.fromEntries(planes.map(plane=>[plane,nearest(item,plane,item.change_indices[plane])])) as Record<Plane,number>);setSelected(present.map(label=>label.id));setFocus(true);setZoom(2)}
  const change=item.change_indices,axis=axes[plane]
  const origin=focus?plane==='sagittal'?`${change.coronal/item.shape[1]*100}% ${(1-change.axial/item.shape[2])*100}%`:plane==='coronal'?`${(1-change.sagittal/item.shape[0])*100}% ${(1-change.axial/item.shape[2])*100}%`:`${(1-change.sagittal/item.shape[0])*100}% ${(1-change.coronal/item.shape[1])*100}%`:'50% 50%'
  const metadata=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(item,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`${item.id}_research_audit.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const labelControls=<><div className="vd-label-heading"><span>Visible vertebrae</span><button onClick={()=>setSelected(selected.length?[]:present.map(label=>label.id))}>{selected.length?'Hide all':'Show all'}</button></div><p className="vd-label-hint">Shared by slices and 3D surfaces</p><div className="vd-label-list">{present.map(label=><label key={label.id}><input type="checkbox" checked={selected.includes(label.id)} onChange={()=>setSelected(values=>values.includes(label.id)?values.filter(id=>id!==label.id):[...values,label.id])}/><i style={{background:label.color}}/><b>{labelName(label.name)}</b><small>{label.after_volume_ml.toFixed(1)} mL</small></label>)}</div></>
  return <div className="vd">
    <header className="vd-topbar"><a href="/" className="vd-author"><span>HC</span> Hongkang Chu</a><div className="vd-breadcrumb"><a href="/projects/">Projects</a><ChevronRight size={13}/><b>Vertebrae Study</b></div><a className="vd-home" href="/"><ArrowLeft size={14}/> Back to homepage</a></header>
    <aside className="vd-sidebar"><div className="vd-workspace-title">RESEARCH WORKSPACE</div><nav><a href="#comparison" className="active"><ScanLine size={16}/> Prediction comparison</a><a href="#audit"><Table2 size={16}/> Quantitative audit</a><a href="#geometry"><Layers size={16}/> 3D anatomy</a><a href="#method"><FlaskConical size={16}/> Method & sources</a></nav>
      <div className="vd-case-picker"><label htmlFor="vd-case">Official demo scan</label><select id="vd-case" aria-label="Select CT case" value={caseId} onChange={event=>setCaseId(event.target.value)}>{manifest.cases.map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select><span><i/> Authentic model predictions</span></div>
      <button className="vd-mobile-label-toggle" onClick={()=>setLabelsOpen(value=>!value)} aria-expanded={labelsOpen}><Layers size={15}/> Visible labels <span>{selected.length}</span></button>
      <div className={`vd-label-controls${labelsOpen?' vd-label-controls-open':''}`}>{labelControls}</div>
      <div className="vd-sidebar-footer"><FlaskConical size={17}/><span>Independent research warmup<small>SuPreM · AbdomenAtlasDemo</small></span></div>
    </aside>
    <main className="vd-main" id="main">
      <div className="vd-page-heading"><div><div className="vd-eyebrow">MEDICAL IMAGING / INDEPENDENT STUDY</div><h1>Vertebrae Study</h1><p>SuPreM vertebrae segmentation and postprocessing.</p></div><button className="vd-button vd-secondary" onClick={metadata}><Download size={15}/> Export audit</button></div>
      <div className="vd-metrics"><div><span>Predicted vertebrae <Layers size={15}/></span><strong>{present.length}<small> / 24 labels</small></strong><p>{item.id} · original {item.original_orientation.join('')} grid</p></div><div><span>Connected components <Activity size={15}/></span><strong>{item.before_components}<em>→</em>{item.after_components}</strong><p>Before → after · 26-connectivity</p></div><div><span>Removed prediction <SlidersHorizontal size={15}/></span><strong>{volume.toFixed(3)}<small> mL</small></strong><p>{number(item.removed_voxels)} voxels removed · {item.added_voxels} added</p></div><div><span>Labels for review <FlaskConical size={15}/></span><strong>{flagged.length}<small> / {present.length} present</small></strong><p>Fragmentation, boundary or identity cues</p></div></div>
      <div className="vd-research-note"><FlaskConical size={14}/><span>Pretrained inference + automatic postprocessing. No manual reference labels are available; connectivity changes do not establish improved accuracy.</span></div>
      <section className="vd-card vd-comparison" id="comparison"><div className="vd-card-heading"><div><h2>Before / after comparison</h2><p>{item.shape.join(' × ')} voxels · {item.spacing_mm.map(value=>value.toFixed(3)).join(' × ')} mm</p></div><span className="vd-badge">Synchronized CT views</span></div>
        <div className="vd-viewer-toolbar"><div className="vd-segmented vd-plane-tabs">{planes.map(value=><button key={value} className={plane===value?'active':''} onClick={()=>setPlane(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div><button className="vd-button vd-inspect" onClick={inspect}><Focus size={14}/> Inspect an edit</button><div className="vd-presets">{Object.entries(presets).map(([name,[width,center]])=><button key={name} className={width===windowWidth&&center===level?'active':''} onClick={()=>{setWindowWidth(width);setLevel(center)}}>{name}</button>)}</div></div>
        <div className="vd-slice-grid">{(['raw','refined','changes'] as const).map(stage=><PixelSlice key={stage} frame={frame} stage={stage} plane={plane} windowWidth={windowWidth} level={level} opacity={opacity} selected={selected} labels={item.labels} zoom={zoom} origin={origin}/>)}</div>
        <div className="vd-viewer-controls"><label className="vd-slice-slider"><span>{plane[0].toUpperCase()+plane.slice(1)} slice <b>{frame.index+1} / {item.shape[axis]}</b></span><input type="range" aria-label="CT slice" min={0} max={frames.length-1} value={position} onChange={event=>{setPositions(values=>({...values,[plane]:Number(event.target.value)}));setFocus(false)}}/><small>{frames.length} sampled native slices · includes edited regions</small></label><label className="vd-number-control">Window<input type="number" aria-label="HU window" min={1} max={4000} value={windowWidth} onChange={event=>setWindowWidth(Math.max(1,Math.min(4000,Number(event.target.value))))}/><small>HU</small></label><label className="vd-number-control">Level<input type="number" aria-label="HU level" min={-1500} max={2000} value={level} onChange={event=>setLevel(Math.max(-1500,Math.min(2000,Number(event.target.value))))}/><small>HU</small></label><label className="vd-opacity"><span>Mask <b>{Math.round(opacity*100)}%</b></span><input type="range" aria-label="Mask opacity" min={0} max={1} step={.05} value={opacity} onChange={event=>setOpacity(Number(event.target.value))}/></label><div className="vd-zoom"><button aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(value=>Math.max(1,value-.5))}><ZoomOut size={16}/></button><button aria-label="Reset slice zoom" onClick={()=>{setZoom(1);setFocus(false)}}>{Math.round(zoom*100)}%</button><button aria-label="Zoom in" disabled={zoom>=3} onClick={()=>setZoom(value=>Math.min(3,value+.5))}><ZoomIn size={16}/></button></div></div>
      </section>
      <div className="vd-analysis-grid"><section className="vd-card vd-audit" id="audit"><div className="vd-card-heading"><div><h2>Connectivity audit</h2><p>Per-vertebra changes on the full-resolution grid</p></div><select aria-label="Audit label scope" value={scope} onChange={event=>setScope(event.target.value)}><option value="all">All present labels</option><option value="flagged">Review flags</option></select></div><ComponentsChart item={item} onSelect={id=>setSelected([id])}/><div className="vd-table-scroll"><table><thead><tr><th>Vertebra</th><th>Components</th><th>Volume, mL</th><th>Removed</th><th>Review</th></tr></thead><tbody>{rows.map(label=><tr key={label.id} className={selected.length===1&&selected[0]===label.id?'vd-row-selected':''}><td><button onClick={()=>setSelected([label.id])}><i style={{background:label.color}}/>{labelName(label.name)}</button></td><td>{label.before_components}<span>→</span>{label.after_components}</td><td>{label.before_volume_ml.toFixed(2)}<span>→</span>{label.after_volume_ml.toFixed(2)}</td><td>{number(label.removed_voxels)}</td><td>{label.flags.filter(flag=>flag!=='not_predicted_in_scan').map(flag=><small key={flag} className="vd-flag" title={flag}>{flagNames[flag]||flag}</small>)}{!label.flags.length&&<span className="vd-clear"><Check size={11}/> No flags</span>}</td></tr>)}</tbody></table></div><p className="vd-footnote">Heuristic flags prompt review. Fewer components do not prove anatomical correctness.</p></section><SurfaceView item={item} selected={selected}/></div>
      <section className="vd-card vd-method" id="method"><div className="vd-card-heading"><div><h2>Method & evidence</h2><p>An auditable first baseline, with explicit limits</p></div><a href={manifest.taskUrl} target="_blank" rel="noreferrer">Original warmup <ArrowUpRight size={14}/></a></div><div className="vd-method-grid"><div><span>01 / INPUT</span><h3>Official CT + pretrained labels</h3><p>Two AbdomenAtlasDemo scans, segmented with the SuPreM vertebrae checkpoint. Original IDs 1–24 and output geometry are retained.</p><details><summary>File hashes & provenance</summary>{Object.entries(item.hashes).map(([name,hash])=><p className="vd-hash" key={name}><b>{name.replace('_sha256','')}</b><code>{hash}</code></p>)}</details></div><div><span>02 / REFINEMENT</span><h3>Small, separated components</h3><p>Remove a component only when it is ≤1% of its label's largest component, ≥3 mm away, and clear of the scan boundaries.</p><div className="vd-method-tags"><span>No identity reassignment</span><span>Hole filling off</span></div></div><div><span>03 / LIMITS</span><h3>Review the anatomy</h3><p>Connected leakage, substantial fragments, missing vertebrae and incorrect identities can remain. The thresholds are engineering heuristics, without a ground-truth accuracy benchmark.</p></div></div>
        <div className="vd-downloads"><a href={manifest.downloads.script} download><FileCode2 size={15}/> Postprocessing script</a><a href={manifest.downloads.csv} download><Table2 size={15}/> Per-label CSV</a><a href={manifest.downloads.masks} download><Layers size={15}/> Refined masks</a><a href={item.comparisonPdf} target="_blank" rel="noreferrer"><ScanLine size={15}/> Comparison figure <ArrowUpRight size={12}/></a></div>
      </section>
      <footer className="vd-page-footer"><span>Independent study by Hongkang Chu · 06 Oct 2026</span><span>Task source: <a href="https://www.zongweiz.com/opportunity" target="_blank" rel="noreferrer">Zongwei Zhou’s lab · JHU</a> · <a href={manifest.taskUrl} target="_blank" rel="noreferrer">SuPreM warmup</a> · <a href={manifest.dataUrl}>AbdomenAtlasDemo</a> · <a href={manifest.upstreamLicenseUrl} target="_blank" rel="noreferrer">Upstream license</a></span></footer>
    </main>
  </div>
}
